spring:
    cloud:
        nacos:
            discovery:
                server-addr: 172.16.90.37:8848
                namespace: 6a836813-fce1-47a7-9528-7fdc02960fe4
                group: DEFAULT_GROUP
            config:
                server-addr: ${spring.cloud.nacos.discovery.server-addr}
                namespace: ${spring.cloud.nacos.discovery.namespace}
                group: ${spring.cloud.nacos.discovery.group}
                file-extension: yml
                name: application
                enabled: false
    application:
        name: ecif-tran-per
server:
    port: 6002
logging:
    file:
        name: ${spring.application.name}
        path: ../udp-logs/${spring.application.name}/appLogs
    level:
        root: INFO
        springfox.documentation.spring.web.readers.operation: 'OFF'
